from typing import List, Optional, Dict, Any
from datetime import datetime, timedelta, timezone
from uuid import UUID
import logging

from app.api.schemas.visitor_snapshot import (
    VisitorSnapshotRequest, 
    VisitorSnapshotResponse, 
    VisitorSummaryEntry,
    NoteCriteria,
    FamilyCriteria
)
from app.services.member_service import MemberService
from app.agents.followup_note_agent import FollowupNoteAgent
from app.data.models.member_service_models import PersonProfile
from app.api.schemas.event_schemas import VisitorContextData, FamilyScenario
from app.services.visitor_context_builder import VisitorContextBuilder

import asyncio
from concurrent.futures import ThreadPoolExecutor

logger = logging.getLogger(__name__)

class VisitorSnapshotService:
    """Service for generating visitor snapshots with AI-powered summaries"""
    
    def __init__(self, schema_name: str):
        """Initialize the visitor snapshot service
        
        Args:
            schema_name: The tenant-specific schema name
        """
        self.schema_name = schema_name
        self.member_service = MemberService(schema_name)
        self.followup_agent = FollowupNoteAgent(f"visitor_snapshot_{schema_name}", "v1")
        self.context_builder = VisitorContextBuilder(schema_name)
        
    async def initialize(self) -> None:
        """Initialize the service and its dependencies"""
        await self.member_service.initialize()
        logger.info(f"Visitor snapshot service initialized for schema: {self.schema_name}")
    
    async def close(self) -> None:
        """Close the service and its dependencies"""
        await self.member_service.close()
        logger.info("Visitor snapshot service closed")
    
    # =============================================================================
    # MAIN PUBLIC METHODS
    # =============================================================================
    
    async def get_visitor_snapshots(
        self,
        request: VisitorSnapshotRequest,
        tenant_id: str
    ) -> VisitorSnapshotResponse:
        """Generate visitor snapshots with enhanced criteria support"""
        try:
            # Fetch visitors based on date range
            visitors = await self._fetch_visitors_by_date_range(
                tenant_id, 
                request.date_range_start, 
                request.date_range_end
            )
            
            if not visitors:
                return VisitorSnapshotResponse(
                    entries=[],
                    total_count=0,
                    page=request.page,
                    has_more=False,
                    ai_disclaimer="No visitors found for the specified criteria."
                )
            
            # Apply family grouping based on criteria
            if request.family_criteria == FamilyCriteria.GROUPED_BY_FAMILY:
                grouped_visitors = self._group_visitors_by_family(visitors)
                summary_entries = await self._create_family_summary_entries_concurrent(
                    list(grouped_visitors.values()), 
                    tenant_id,
                    request.note_criteria,
                    request.report_purpose
                )
            else:
                # Individual processing
                summary_entries = await self._create_individual_summary_entries_concurrent(
                    visitors,
                    tenant_id, 
                    request.note_criteria,
                    request.report_purpose
                )
            
            # Apply pagination
            total_count = len(summary_entries)
            start_idx = (request.page - 1) * request.limit
            end_idx = start_idx + request.limit
            paginated_entries = summary_entries[start_idx:end_idx]
            
            has_more = end_idx < total_count
            
            return VisitorSnapshotResponse(
                entries=paginated_entries,
                total_count=total_count,
                page=request.page,
                has_more=has_more,
                ai_disclaimer="This summary was generated by AI and may not capture all nuances. Please review the full visitor context for complete information."
            )
            
        except Exception as e:
            logger.error(f"Error generating visitor snapshots: {str(e)}")
            raise
    
    # =============================================================================
    # DATA FETCHING METHODS
    # =============================================================================
    
    async def _fetch_visitors_by_date_range(
        self, 
        tenant_id: str, 
        start_date: Optional[datetime], 
        end_date: Optional[datetime]
    ) -> List[PersonProfile]:
        """Fetch visitors within the specified date range"""
        try:
            # Calculate date range if not provided
            if not start_date or not end_date:
                end_date = datetime.now(timezone.utc)
                start_date = end_date - timedelta(days=90)  # Default to last 90 days
            
            # Get visitors from member service
            visitors = await self.member_service.get_visitors_by_date_range(
                start_date=start_date,
                end_date=end_date,
                limit=1000  # Get more than needed for accurate pagination
            )
            
            return visitors
            
        except Exception as e:
            logger.error(f"Error fetching visitors by date range: {e}")
            raise
    
    def _group_visitors_by_family(self, visitors: List[PersonProfile]) -> Dict[str, List[PersonProfile]]:
        """Group visitors by family ID
        
        Args:
            visitors: List of visitor profiles
            
        Returns:
            Dictionary mapping family keys to lists of family members
        """
        family_groups = {}
        
        for visitor in visitors:
            # Use fam_id if available, otherwise treat as individual family
            family_key = str(visitor.fam_id) if visitor.fam_id else f"individual_{visitor.id}"
            
            if family_key not in family_groups:
                family_groups[family_key] = []
            family_groups[family_key].append(visitor)
        
        return family_groups
    
    # =============================================================================
    # FAMILY PROCESSING METHODS
    # =============================================================================
    
    async def _create_family_summary_entries_concurrent(
        self, 
        family_groups: List[List[PersonProfile]],
        tenant_id: str,
        note_criteria: NoteCriteria,
        report_purpose: Optional[str]
    ) -> List[VisitorSummaryEntry]:
        """Create family summary entries with concurrent AI processing
        
        Args:
            family_groups: List of family member groups
            tenant_id: Tenant identifier
            note_criteria: Note filtering criteria
            report_purpose: Purpose of the report
            
        Returns:
            List of visitor summary entries
        """
        # Process families concurrently with limited concurrency
        semaphore = asyncio.Semaphore(5)  # Limit to 5 concurrent AI calls
        
        async def process_family_with_semaphore(family_members):
            async with semaphore:
                return await self._create_family_summary_entry(
                    family_members, tenant_id, note_criteria, report_purpose
                )
        
        # Create tasks for concurrent processing
        tasks = [
            process_family_with_semaphore(family_members) 
            for family_members in family_groups
        ]
        
        # Execute all tasks concurrently
        entries = await asyncio.gather(*tasks, return_exceptions=True)
        
        # Handle any exceptions and create fallback entries
        result_entries = []
        for i, entry in enumerate(entries):
            if isinstance(entry, Exception):
                logger.error(f"Error processing family group {i}: {entry}")
                # Create fallback entry for the family
                result_entries.append(self._create_fallback_family_entry(
                    family_groups[i], report_purpose
                ))
            else:
                result_entries.append(entry)
        
        return result_entries
    
    async def _create_family_summary_entry(
        self, 
        family_members: List[PersonProfile],
        tenant_id: str,
        note_criteria: NoteCriteria,
        report_purpose: Optional[str]
    ) -> VisitorSummaryEntry:
        """Create a summary entry for a family group
        
        Args:
            family_members: List of family member profiles
            tenant_id: Tenant identifier
            note_criteria: Note filtering criteria
            report_purpose: Purpose of the report
            
        Returns:
            VisitorSummaryEntry for the family
        """
        try:
            # Determine primary contact (first visitor or family head)
            primary_visitor = family_members[0]
            for member in family_members:
                if hasattr(member, 'is_family_head') and member.is_family_head:
                    primary_visitor = member
                    break
            
            # Generate AI summary for the entire family
            ai_summary = await self.generate_family_ai_summary(
                family_members, primary_visitor, tenant_id, note_criteria, report_purpose
            )
            
            # Build family member names
            family_member_names = [f"{member.first_name} {member.last_name}" for member in family_members]
            
            # Determine contact person
            contact_person = f"{primary_visitor.first_name} {primary_visitor.last_name}"
            
            # Extract sentiment from AI summary
            sentiment = self._extract_sentiment_from_summary(ai_summary)
            
            # Use the earliest visit date from family members
            earliest_visit = min(
                (member.created_at for member in family_members if member.created_at),
                default=primary_visitor.created_at
            )
            
            # Determine notes scope description
            notes_scope = (
                "First visit notes and welcome form data only" 
                if note_criteria == NoteCriteria.FIRST_VISIT_ONLY 
                else "All notes recorded to date"
            )
            
            return VisitorSummaryEntry(
                visitor_id=primary_visitor.id,
                name=f"{contact_person} Family" if len(family_members) > 1 else contact_person,
                first_visit_date=earliest_visit,
                family_size=len(family_members),
                family_members=family_member_names,
                contact_person=contact_person,
                visitor_summary=ai_summary,
                sentiment_classification=sentiment,
                notes_scope_used=notes_scope,
                report_purpose=report_purpose or "Family visitor follow-up and engagement tracking",
                is_expanded=False
            )
            
        except Exception as e:
            logger.error(f"Error creating family summary entry: {e}")
            return self._create_fallback_family_entry(family_members, report_purpose)
    
    async def generate_family_ai_summary(
        self, 
        family_members: List[PersonProfile],
        primary_visitor: PersonProfile,
        tenant_id: str,
        note_criteria: NoteCriteria,
        report_purpose: Optional[str]
    ) -> str:
        """Generate AI-powered summary for a family group
        
        Args:
            family_members: List of family member profiles
            primary_visitor: The primary contact person
            tenant_id: Tenant identifier
            note_criteria: Note filtering criteria
            report_purpose: Purpose of the report
            
        Returns:
            AI-generated summary string
        """
        try:
            # Build family context for AI processing
            family_context = await self._build_family_context(
                family_members, primary_visitor, tenant_id, note_criteria
            )
            
            # Use the followup note agent to generate a family summary
            ai_note_data = await self.followup_agent.generate_visitor_snapshot_summary(family_context)
            
            # Extract the natural summary from the AI note
            return ai_note_data.get("natural_summary", "No summary available")
            
        except Exception as e:
            logger.error(f"Error generating family AI summary: {e}")
            return self._create_fallback_family_summary(family_members, primary_visitor)
    
    async def _build_family_context(
        self, 
        family_members: List[PersonProfile], 
        primary_visitor: PersonProfile,
        tenant_id: str,
        note_criteria: NoteCriteria
    ) -> VisitorContextData:
        """Build family context data for AI processing
        
        Args:
            family_members: List of family member profiles
            primary_visitor: The primary contact person
            tenant_id: Tenant identifier
            note_criteria: Note filtering criteria
            
        Returns:
            VisitorContextData for AI processing
        """
        try:
            # Get welcome form data for primary visitor
            welcome_form_data = await self.member_service.get_visitor_welcome_form_data(str(primary_visitor.id))
            
            # Create proper FamilyScenario object
            scenario_info = FamilyScenario(
                scenario_type="family_visitor_snapshot",
                primary_person_id=str(primary_visitor.id),
                fam_id=str(primary_visitor.fam_id) if primary_visitor.fam_id else str(primary_visitor.id),
                context_strategy="family_visitor_snapshot_context",
                family_members_to_query=[str(member.id) for member in family_members],
                family_head_id=str(primary_visitor.id)
            )
            
            # Build family context
            family_context_data = {
                "visitor_profile": {
                    "person_id": str(primary_visitor.id),
                    "first_name": primary_visitor.first_name,
                    "last_name": primary_visitor.last_name,
                    "email": primary_visitor.email,
                    "phone": primary_visitor.phone,
                    "created_at": primary_visitor.created_at.isoformat() if primary_visitor.created_at else None
                },
                "visitor_welcome_form": welcome_form_data or {},
                "family_members": [
                    {
                        "person_id": str(member.id),
                        "first_name": member.first_name,
                        "last_name": member.last_name,
                        "relationship": getattr(member, 'relationship', 'Family Member'),
                        "created_at": member.created_at.isoformat() if member.created_at else None
                    }
                    for member in family_members
                ],
                "scenario_info": scenario_info,
                "public_teams": [],
                "public_groups": [],
                "upcoming_events": []
            }
            
            return VisitorContextData(**family_context_data)
            
        except Exception as e:
            logger.error(f"Error building family context: {e}")
            # Return minimal context with proper FamilyScenario
            fallback_scenario = FamilyScenario(
                scenario_type="family_visitor_snapshot",
                primary_person_id=str(primary_visitor.id),
                fam_id=str(primary_visitor.id),
                context_strategy="family_visitor_snapshot_context",
                family_members_to_query=[],
                family_head_id=str(primary_visitor.id)
            )
            
            return VisitorContextData(
                visitor_profile={
                    "person_id": str(primary_visitor.id),
                    "first_name": primary_visitor.first_name or "Unknown",
                    "last_name": primary_visitor.last_name or "Visitor"
                },
                visitor_welcome_form={},
                family_members=[],
                scenario_info=fallback_scenario
            )
    
    # =============================================================================
    # INDIVIDUAL PROCESSING METHODS
    # =============================================================================
    
    async def _create_individual_summary_entries_concurrent(
        self,
        visitors: List[PersonProfile],
        tenant_id: str,
        note_criteria: NoteCriteria,
        report_purpose: Optional[str]
    ) -> List[VisitorSummaryEntry]:
        """Create individual summary entries with note criteria support"""
        semaphore = asyncio.Semaphore(5)  # Limit concurrent AI calls
        
        async def process_individual_visitor(visitor):
            async with semaphore:
                try:
                    return await self._create_individual_visitor_summary_entry(
                        visitor, 
                        tenant_id,
                        note_criteria,
                        report_purpose
                    )
                except Exception as e:
                    logger.error(f"Error processing individual visitor {visitor.id}: {str(e)}")
                    return self._create_fallback_individual_entry(visitor, report_purpose)
        
        tasks = [process_individual_visitor(visitor) for visitor in visitors]
        return await asyncio.gather(*tasks)
    
    async def _create_individual_visitor_summary_entry(
        self,
        visitor: PersonProfile,
        tenant_id: str,
        note_criteria: NoteCriteria,
        report_purpose: Optional[str]
    ) -> VisitorSummaryEntry:
        """Create summary entry for individual visitor with note criteria"""
        try:
            # Build context based on note criteria
            visitor_context = await self._build_individual_visitor_context(
                visitor, 
                tenant_id,
                note_criteria
            )
            
            # Generate AI summary
            ai_summary = await self.generate_individual_ai_summary(
                visitor_context, 
                report_purpose or "Individual visitor follow-up and engagement tracking"
            )
            
            # Determine notes scope description
            notes_scope = (
                "First visit notes and welcome form data only" 
                if note_criteria == NoteCriteria.FIRST_VISIT_ONLY 
                else "All notes recorded to date"
            )
            
            return VisitorSummaryEntry(
                visitor_id=visitor.id,
                name=f"{visitor.first_name} {visitor.last_name}",
                first_visit_date=visitor.created_at,
                family_size=1,
                family_members=[f"{visitor.first_name} {visitor.last_name}"],
                contact_person=f"{visitor.first_name} {visitor.last_name}",
                visitor_summary=ai_summary,
                sentiment_classification=self._extract_sentiment_from_summary(ai_summary),
                notes_scope_used=notes_scope,
                report_purpose=report_purpose,
                is_expanded=False
            )
            
        except Exception as e:
            logger.error(f"Error creating individual visitor summary: {str(e)}")
            return self._create_fallback_individual_entry(visitor, report_purpose)
    
    async def generate_individual_ai_summary(
        self,
        visitor_context: VisitorContextData,
        report_purpose: str
    ) -> str:
        """Generate AI summary for individual visitor"""
        try:
            # Use the followup note agent to generate a summary
            ai_note_data = await self.followup_agent.generate_visitor_snapshot_summary(visitor_context)
            
            # Extract the natural summary from the AI note
            return ai_note_data.get("natural_summary", "No summary available")
            
        except Exception as e:
            logger.error(f"Error generating individual AI summary: {e}")
            return f"Unable to generate AI summary. Basic visitor information available."
    
    async def _build_individual_visitor_context(
        self,
        visitor: PersonProfile,
        tenant_id: str,
        note_criteria: NoteCriteria
    ) -> VisitorContextData:
        """Build context for individual visitor based on note criteria"""
        try:
            # Get visitor profile
            visitor_profile = {
                "person_id": str(visitor.id),
                "first_name": visitor.first_name,
                "last_name": visitor.last_name,
                "email": visitor.email,
                "phone": visitor.phone,
                "created_at": visitor.created_at.isoformat() if visitor.created_at else None
            }
            
            # Get welcome form data
            welcome_form_data = await self.member_service.get_visitor_welcome_form_data(str(visitor.id))
            
            # Get notes based on criteria
            notes = []
            if note_criteria == NoteCriteria.FIRST_VISIT_ONLY:
                # Only get notes from first visit date
                if hasattr(self.context_builder, 'get_visitor_notes_by_date'):
                    notes = await self.context_builder.get_visitor_notes_by_date(
                        visitor.id, 
                        tenant_id,
                        visitor.created_at
                    )
            else:
                # Get all notes
                if hasattr(self.context_builder, 'get_all_visitor_notes'):
                    notes = await self.context_builder.get_all_visitor_notes(
                        visitor.id, 
                        tenant_id
                    )
            
            # Create scenario info
            scenario_info = FamilyScenario(
                scenario_type="individual_visitor_snapshot",
                primary_person_id=str(visitor.id),
                fam_id=str(visitor.fam_id) if visitor.fam_id else str(visitor.id),
                context_strategy="individual_visitor",
                family_members_to_query=[str(visitor.id)],
                family_head_id=str(visitor.id)
            )
            
            return VisitorContextData(
                visitor_profile=visitor_profile,
                visitor_welcome_form=welcome_form_data or {},
                family_members=[],  # Individual context
                scenario_info=scenario_info
            )
            
        except Exception as e:
            logger.error(f"Error building individual visitor context: {str(e)}")
            # Return fallback context
            return self._create_fallback_individual_context(visitor)
    
    def _create_fallback_individual_context(self, visitor: PersonProfile) -> VisitorContextData:
        """Create fallback context for individual visitor"""
        fallback_scenario = FamilyScenario(
            scenario_type="individual_visitor_snapshot",
            primary_person_id=str(visitor.id),
            fam_id=str(visitor.id),
            context_strategy="individual_visitor",
            family_members_to_query=[],
            family_head_id=str(visitor.id)
        )
        
        return VisitorContextData(
            visitor_profile={
                "person_id": str(visitor.id),
                "first_name": visitor.first_name or "Unknown",
                "last_name": visitor.last_name or "Visitor"
            },
            visitor_welcome_form={},
            family_members=[],
            scenario_info=fallback_scenario
        )
    
    # =============================================================================
    # FALLBACK AND UTILITY METHODS
    # =============================================================================
    
    def _create_fallback_family_entry(
        self, 
        family_members: List[PersonProfile],
        report_purpose: Optional[str]
    ) -> VisitorSummaryEntry:
        """Create a fallback visitor entry when family processing fails
        
        Args:
            family_members: List of family member profiles
            report_purpose: Purpose of the report
            
        Returns:
            Basic VisitorSummaryEntry for the family
        """
        primary_visitor = family_members[0]
        family_member_names = [f"{member.first_name} {member.last_name}" for member in family_members]
        contact_person = f"{primary_visitor.first_name} {primary_visitor.last_name}"
        
        return VisitorSummaryEntry(
            visitor_id=primary_visitor.id,
            name=f"{contact_person} Family" if len(family_members) > 1 else contact_person,
            first_visit_date=primary_visitor.created_at,
            family_size=len(family_members),
            family_members=family_member_names,
            contact_person=contact_person,
            visitor_summary=self._create_fallback_family_summary(family_members, primary_visitor),
            sentiment_classification="Neutral",
            notes_scope_used="Basic family visitor profile data",
            report_purpose=report_purpose or "Family visitor follow-up and engagement tracking",
            is_expanded=False
        )
    
    def _create_fallback_family_summary(
        self, 
        family_members: List[PersonProfile], 
        primary_visitor: PersonProfile
    ) -> str:
        """Create a fallback summary when family AI generation fails
        
        Args:
            family_members: List of family member profiles
            primary_visitor: The primary contact person
            
        Returns:
            Basic fallback summary for the family
        """
        if len(family_members) == 1:
            name = f"{primary_visitor.first_name} {primary_visitor.last_name}"
            visit_date = primary_visitor.created_at.strftime("%B %d, %Y") if primary_visitor.created_at else "recently"
            return f"{name} visited our church {visit_date}. They are a new visitor to our community and we look forward to connecting with them further."
        else:
            family_name = f"{primary_visitor.first_name} {primary_visitor.last_name} Family"
            visit_date = primary_visitor.created_at.strftime("%B %d, %Y") if primary_visitor.created_at else "recently"
            member_count = len(family_members)
            return f"The {family_name} ({member_count} members) visited our church {visit_date}. They are new visitors to our community and we look forward to connecting with them further."
    
    def _create_fallback_individual_entry(
        self, 
        visitor: PersonProfile,
        report_purpose: Optional[str]
    ) -> VisitorSummaryEntry:
        """Create fallback entry for individual visitor"""
        name = f"{visitor.first_name} {visitor.last_name}"
        
        return VisitorSummaryEntry(
            visitor_id=visitor.id,
            name=name,
            first_visit_date=visitor.created_at,
            family_size=1,
            family_members=[name],
            contact_person=name,
            visitor_summary=self._create_fallback_summary(visitor),
            sentiment_classification="Neutral",
            notes_scope_used="Basic visitor profile data",
            report_purpose=report_purpose or "Visitor follow-up and engagement tracking",
            is_expanded=False
        )
    
    def _create_fallback_summary(self, visitor: PersonProfile) -> str:
        """Create a fallback summary when AI generation fails
        
        Args:
            visitor: The visitor profile
            
        Returns:
            Basic fallback summary
        """
        name = f"{visitor.first_name} {visitor.last_name}"
        visit_date = visitor.created_at.strftime("%B %d, %Y") if visitor.created_at else "recently"
        return f"{name} visited our church {visit_date}. They are a new visitor to our community and we look forward to connecting with them further."
    
    def _extract_sentiment_from_summary(self, summary: str) -> str:
        """Extract sentiment classification from AI summary
        
        Args:
            summary: The AI-generated summary
            
        Returns:
            Sentiment classification string
        """
        summary_lower = summary.lower()
        
        # Simple keyword-based sentiment analysis
        positive_keywords = ['positive', 'enjoyed', 'excited', 'interested', 'happy', 'pleased']
        negative_keywords = ['concerned', 'worried', 'disappointed', 'frustrated', 'negative']
        
        positive_count = sum(1 for keyword in positive_keywords if keyword in summary_lower)
        negative_count = sum(1 for keyword in negative_keywords if keyword in summary_lower)
        
        if positive_count > negative_count:
            return "Positive"
        elif negative_count > positive_count:
            return "Negative"
        else:
            return "Neutral"