apiVersion: apps/v1
kind: Deployment
metadata:
  name: vecapp-ai-depl
  namespace: default
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: vecapp/analytics:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: DATABASE_URL
            - name: REDIS_URL 
              valueFrom:
                secretKeyRef:
                  name: redis-creds
                  key: REDIS_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-creds
                  key: SECRET_KEY
            - name: NLP_SERVICE_URL
              value: http://nlp-service:8501
            - name: PDF_SERVICE_URL  
              value: http://pdf-service:8080
            - name: NODE_ENV
              value: production
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: K8S_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: K8S_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: $(HOST_IP):4317
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=ANALYTICS_SERVICE,deployment.environment=$(NODE_ENV),k8s.pod.ip=$(K8S_POD_IP),k8s.pod.uid=$(K8S_POD_UID)
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/v1/analytics/health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/v1/analytics/health  
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
      imagePullSecrets:
        - name: docker-creds
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%