"""initial_public_schema

Revision ID: 68775bd8f1fd
Revises: 
Create Date: 2025-07-15 20:44:53.143500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68775bd8f1fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """initial_public_schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the op.drop_table('alembic_version') line - this is incorrect
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """initial_public_schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the alembic_version table creation - this is managed by Alembic itself
    pass
    # ### end Alembic commands ###