"""initial migration with new setup

Revision ID: 7b675e5e49ac
Revises: 
Create Date: 2025-07-21 01:33:23.013563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b675e5e49ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """initial migration with new setup"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=False),
    sa.Column('tenant_type', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('admin_first_name', sa.String(length=255), nullable=True),
    sa.Column('admin_last_name', sa.String(length=255), nullable=True),
    sa.Column('admin_email', sa.String(length=255), nullable=True),
    sa.Column('admin_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('street_address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('tenant_country_code', sa.String(length=10), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=255), nullable=True),
    sa.Column('tenant_address', sa.String(length=255), nullable=True),
    sa.Column('tenant_city', sa.String(length=255), nullable=True),
    sa.Column('tenant_state', sa.String(length=255), nullable=True),
    sa.Column('tenant_country', sa.String(length=255), nullable=True),
    sa.Column('tenant_timezone', sa.String(length=255), nullable=True),
    sa.Column('church_size', sa.String(length=50), nullable=True),
    sa.Column('parish_name', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('tenant_head', sa.UUID(), nullable=True),
    sa.Column('tenant_status', sa.String(length=255), nullable=True),
    sa.Column('adult_consent', sa.Integer(), server_default=sa.text('16'), nullable=False),
    sa.Column('member_data_retention_period', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('team_deletion_grace_period', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('group_deletion_grace_period', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('subscription_type', sa.String(length=50), nullable=True),
    sa.Column('subscription_plan', sa.String(length=255), nullable=True),
    sa.Column('subscription_status', sa.String(length=255), nullable=True),
    sa.Column('subscription_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subscription_date', sa.Date(), nullable=True),
    sa.Column('subscription_start_date', sa.Date(), nullable=True),
    sa.Column('subscription_end_date', sa.Date(), nullable=True),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('schema_provisioned', sa.Boolean(), nullable=False),
    sa.Column('migrations_applied', sa.Boolean(), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('tenant_date_created', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('api_key', name='tenant_registry_api_key_unique'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('domain', name='tenant_registry_domain_unique'),
    sa.UniqueConstraint('schema_name'),
    sa.UniqueConstraint('schema_name', name='tenant_registry_schema_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """initial migration with new setup"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_registry')
    # ### end Alembic commands ###