"""create_tenant_registry_table

Revision ID: 5f58a798b8f3
Revises: 68775bd8f1fd
Create Date: 2025-07-15 23:47:09.805536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f58a798b8f3'
down_revision: Union[str, None] = '68775bd8f1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """create_tenant_registry_table"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=False),
    sa.Column('tenant_type', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_address', sa.String(length=255), nullable=True),
    sa.Column('tenant_city', sa.String(length=255), nullable=True),
    sa.Column('tenant_state', sa.String(length=255), nullable=True),
    sa.Column('tenant_country', sa.String(length=255), nullable=True),
    sa.Column('tenant_country_code', sa.String(length=10), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('tenant_timezone', sa.String(length=255), nullable=True),
    sa.Column('parish_name', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('tenant_head', sa.UUID(), nullable=True),
    sa.Column('tenant_status', sa.String(length=255), nullable=True),
    sa.Column('adult_consent', sa.Integer(), server_default=sa.text('16'), nullable=False),
    sa.Column('member_data_retention_period', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('team_deletion_grace_period', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('group_deletion_grace_period', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('schema_provisioned', sa.Boolean(), nullable=False),
    sa.Column('migrations_applied', sa.Boolean(), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('tenant_date_created', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('api_key', name='tenant_registry_api_key_unique'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('domain', name='tenant_registry_domain_unique'),
    sa.UniqueConstraint('schema_name'),
    sa.UniqueConstraint('schema_name', name='tenant_registry_schema_unique')
    )
    # Remove the op.drop_table('alembic_version') line - this is incorrect
    # ### end Alembic commands ###


def downgrade() -> None:
    """create_tenant_registry_table"""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the alembic_version table creation - this is managed by Alembic itself
    op.drop_table('tenant_registry')
    # ### end Alembic commands ###