"""update ai_recommendation fk

Revision ID: 4b82477c8a2d
Revises: 11399a647250
Create Date: 2025-07-21 09:47:30.310468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b82477c8a2d'
down_revision: Union[str, None] = '11399a647250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """update ai_recommendation fk"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('subscription_amount',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True,
               postgresql_using='subscription_amount::numeric(10,2)')

    # ### end Alembic commands ###


def downgrade() -> None:
    """update ai_recommendation fk"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('subscription_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               postgresql_using='subscription_amount::varchar(20)')

    # ### end Alembic commands ###